#!/bin/sh
export PATH="$PATH:/home/ulrich/.platformio/packages/toolchain-xtensa32/bin"
SYSVIEW_SCRIPT="/home/ulrich/.platformio/packages/framework-espidf/tools/esp_app_trace/sysviewtrace_proc.py"
ELFFILE="/home/ulrich/mysrc/esp32/esp_ajax_if/.pio/build/debug/firmware.elf"
TRACEFILE1="/tmp/pro_cpu.svdat"
TRACEFILE2="/tmp/app_cpu.svdat"
OUTPUTFILE1="pro_cpu.trace"
OUTPUTFILE2="app_cpu.trace"

python3 "$SYSVIEW_SCRIPT" "$TRACEFILE1" "$ELFFILE" > "$OUTPUTFILE1"
python3 "$SYSVIEW_SCRIPT" "$TRACEFILE2" "$ELFFILE" > "$OUTPUTFILE2"
